const c=document.getElementById("game"),x=c.getContext("2d"),M=document.getElementById("money"),L=document.getElementById("location"),msg=document.getElementById("message"),panel=document.getElementById("panel"),pt=document.getElementById("pt"),pc=document.getElementById("pc");let W,H;function size(){W=c.width=innerWidth;H=c.height=innerHeight}addEventListener("resize",size);size();
let S=JSON.parse(localStorage.tdrive||"null")||{money:500000,truck:null,workers:[],deals:0};let p={x:500,y:450,a:0,v:0},keys={};const places={market:[220,220,"MARKET"],showroom:[800,220,"SHOWROOM"],garage:[800,650,"GARAGE"],office:[220,650,"OFFICE"]};const trucks=[["Mini Truck",120000,2.5,2,"🚚"],["City Truck",220000,2.2,4,"🚛"],["Cargo Master",320000,2,6,"🚛"],["Heavy Truck",480000,1.8,10,"🚛"]];const workers=[["রহিম","Driver",50000],["করিম","Mechanic",60000],["সুমন","Manager",90000]];
function save(){localStorage.tdrive=JSON.stringify(S);M.textContent=S.money.toLocaleString()}function say(t){msg.textContent=t;msg.style.display="block";clearTimeout(window.tt);window.tt=setTimeout(()=>msg.style.display="none",2500)}
function near(){for(const k in places){let q=places[k];if(Math.hypot(p.x-q[0],p.y-q[1])<75)return k}return null}
function screen(a,b){return{x:a-cam.x+W/2,y:b-cam.y+H/2}}let cam={x:500,y:450};
function draw(){x.fillStyle="#78a55f";x.fillRect(0,0,W,H);cam.x+=(p.x-cam.x)*.12;cam.y+=(p.y-cam.y)*.12;let roads=[[220,220,800,220],[800,220,800,650],[800,650,220,650],[220,650,220,220]];x.lineWidth=90;x.strokeStyle="#50565b";for(let r of roads){let a=screen(r[0],r[1]),b=screen(r[2],r[3]);x.beginPath();x.moveTo(a.x,a.y);x.lineTo(b.x,b.y);x.stroke()}x.lineWidth=3;x.strokeStyle="#ddd06a";x.setLineDash([18,18]);for(let r of roads){let a=screen(r[0],r[1]),b=screen(r[2],r[3]);x.beginPath();x.moveTo(a.x,a.y);x.lineTo(b.x,b.y);x.stroke()}x.setLineDash([]);for(let k in places){let q=places[k],s=screen(q[0],q[1]);x.fillStyle=k=="market"?"#e0a82b":k=="showroom"?"#438cf5":k=="garage"?"#28b870":"#9a6bea";x.beginPath();x.arc(s.x,s.y,43,0,7);x.fill();x.fillStyle="#fff";x.font="bold 15px Arial";x.textAlign="center";x.fillText(q[2],s.x,s.y+5)}let z=screen(p.x,p.y);x.save();x.translate(z.x,z.y);x.rotate(p.a);x.fillStyle="#263b52";x.fillRect(-27,-15,54,30);x.fillStyle="#64c4e8";x.fillRect(7,-11,18,22);x.fillStyle="#111";for(let a of[-18,18]){x.beginPath();x.arc(a,-17,6,0,7);x.fill();x.beginPath();x.arc(a,17,6,0,7);x.fill()}x.restore()}
function update(dt){if(S.truck){let max=S.truck[2];if(keys.gas)p.v=Math.min(max,p.v+.08);else if(keys.reverse)p.v=Math.max(-max*.5,p.v-.08);else p.v*=.94;if(keys.brake)p.v*=.82;if(Math.abs(p.v)>.03){if(keys.left)p.a-=.035*(p.v/max);if(keys.right)p.a+=.035*(p.v/max);p.x+=Math.cos(p.a)*p.v*60*dt;p.y+=Math.sin(p.a)*p.v*60*dt}}let n=near();L.textContent=n?"📍 "+places[n][2]+" — ক্লিক করুন":"📍 শহরের রাস্তা"}let last=performance.now();function loop(t){let dt=Math.min(.033,(t-last)/1000);last=t;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
function open(t,h){pt.textContent=t;pc.innerHTML=h;panel.classList.remove("hidden")}document.getElementById("close").onclick=()=>panel.classList.add("hidden");
function market(){open("🚛 Truck Market",trucks.map((t,i)=>`<div class="option"><h3>${t[4]} ${t[0]}</h3><p>দাম ৳${t[1].toLocaleString()} | Speed ${t[2]} | Cargo ${t[3]} ton</p><button class="btn buy" onclick="buy(${i})">🚛 কিনুন</button></div>`).join(""))}
window.buy=i=>{let t=trucks[i];if(S.truck)return say("আপনার আগে থেকেই ট্রাক আছে।");if(S.money<t[1])return say("💰 টাকা কম");S.money-=t[1];S.truck=t;save();say("🎉 "+t[0]+" কেনা হয়েছে! এখন গাড়ি চালান।");market()};
function garage(){if(!S.truck)return open("🔧 Garage","<p>আগে MARKET থেকে ট্রাক কিনুন।</p>");let h=`<div class="option"><h3>${S.truck[4]} ${S.truck[0]}</h3><p>Speed ${S.truck[2]} | Cargo ${S.truck[3]} ton</p></div><h3>👷 কাজের লোক রাখুন</h3>`;workers.forEach((w,i)=>h+=`<div class="option"><h3>👷 ${w[0]} — ${w[1]}</h3><p>নিয়োগ ৳${w[2].toLocaleString()}</p><button class="btn hire" onclick="hire(${i})">নিয়োগ করুন</button></div>`);h+=`<div class="option"><h3>নিয়োগ করা লোক: ${S.workers.length}</h3>${S.workers.map(w=>"<p>• "+w[0]+" — "+w[1]+"</p>").join("")||"<p>কেউ নেই</p>"}</div>`;open("🔧 Garage",h)}
window.hire=i=>{let w=workers[i];if(S.workers.some(a=>a[1]==w[1]))return say("এই পদের লোক আছে।");if(S.money<w[2])return say("💰 টাকা কম");S.money-=w[2];S.workers.push(w);save();say("👷 "+w[0]+" নিয়োগ হয়েছে");garage()};
function showroom(){if(!S.truck)return open("🏢 Showroom","<p>ট্রাক নিয়ে এখানে আসুন।</p>");open("🏢 Showroom",`<div class="option"><h3>🚛 ${S.truck[0]}</h3><p>কাস্টমারের কাছে ট্রাক ডিল করে আয় করুন।</p><button class="btn buy" onclick="deal()">🤝 Deal করুন</button></div>`)}
window.deal=()=>{let r=30000+S.truck[3]*6000+S.workers.length*5000;S.money+=r;S.deals++;save();say("🤝 ডিল সফল! আয় ৳"+r.toLocaleString());showroom()};
function office(){open("🏢 Dealer Office",`<div class="option"><h3>📊 ব্যবসার হিসাব</h3><p>ডিল: ${S.deals}</p><p>কাজের লোক: ${S.workers.length}</p><p>টাকা: ৳${S.money.toLocaleString()}</p></div>`)}
c.onclick=()=>{let n=near();if(n=="market")market();if(n=="garage")garage();if(n=="showroom")showroom();if(n=="office")office()};
function bind(id,k){let b=document.getElementById(id);b.onpointerdown=e=>{e.preventDefault();keys[k]=1};b.onpointerup=b.onpointercancel=()=>keys[k]=0}bind("left","left");bind("right","right");bind("gas","gas");bind("brake","brake");bind("reverse","reverse");save();say("🚛 ▲ চাপ দিয়ে গাড়ি চালান।")}
